//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace flyamerica.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class flyamericaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new flyamericaEntities object using the connection string found in the 'flyamericaEntities' section of the application configuration file.
        /// </summary>
        public flyamericaEntities() : base("name=flyamericaEntities", "flyamericaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new flyamericaEntities object.
        /// </summary>
        public flyamericaEntities(string connectionString) : base(connectionString, "flyamericaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new flyamericaEntities object.
        /// </summary>
        public flyamericaEntities(EntityConnection connection) : base(connection, "flyamericaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pilottraining> pilottrainings
        {
            get
            {
                if ((_pilottrainings == null))
                {
                    _pilottrainings = base.CreateObjectSet<pilottraining>("pilottrainings");
                }
                return _pilottrainings;
            }
        }
        private ObjectSet<pilottraining> _pilottrainings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pilottrainings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopilottrainings(pilottraining pilottraining)
        {
            base.AddObject("pilottrainings", pilottraining);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="flyamericaModel", Name="pilottraining")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pilottraining : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pilottraining object.
        /// </summary>
        /// <param name="trainingId">Initial value of the TrainingId property.</param>
        /// <param name="trainingName">Initial value of the TrainingName property.</param>
        /// <param name="trainingShortDescription">Initial value of the TrainingShortDescription property.</param>
        /// <param name="trainingLongDescription">Initial value of the TrainingLongDescription property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static pilottraining Createpilottraining(global::System.Int32 trainingId, global::System.String trainingName, global::System.String trainingShortDescription, global::System.String trainingLongDescription, global::System.Boolean isActive)
        {
            pilottraining pilottraining = new pilottraining();
            pilottraining.TrainingId = trainingId;
            pilottraining.TrainingName = trainingName;
            pilottraining.TrainingShortDescription = trainingShortDescription;
            pilottraining.TrainingLongDescription = trainingLongDescription;
            pilottraining.IsActive = isActive;
            return pilottraining;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TrainingId
        {
            get
            {
                return _TrainingId;
            }
            set
            {
                if (_TrainingId != value)
                {
                    OnTrainingIdChanging(value);
                    ReportPropertyChanging("TrainingId");
                    _TrainingId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TrainingId");
                    OnTrainingIdChanged();
                }
            }
        }
        private global::System.Int32 _TrainingId;
        partial void OnTrainingIdChanging(global::System.Int32 value);
        partial void OnTrainingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TrainingName
        {
            get
            {
                return _TrainingName;
            }
            set
            {
                OnTrainingNameChanging(value);
                ReportPropertyChanging("TrainingName");
                _TrainingName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TrainingName");
                OnTrainingNameChanged();
            }
        }
        private global::System.String _TrainingName;
        partial void OnTrainingNameChanging(global::System.String value);
        partial void OnTrainingNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TrainingShortDescription
        {
            get
            {
                return _TrainingShortDescription;
            }
            set
            {
                OnTrainingShortDescriptionChanging(value);
                ReportPropertyChanging("TrainingShortDescription");
                _TrainingShortDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TrainingShortDescription");
                OnTrainingShortDescriptionChanged();
            }
        }
        private global::System.String _TrainingShortDescription;
        partial void OnTrainingShortDescriptionChanging(global::System.String value);
        partial void OnTrainingShortDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TrainingLongDescription
        {
            get
            {
                return _TrainingLongDescription;
            }
            set
            {
                OnTrainingLongDescriptionChanging(value);
                ReportPropertyChanging("TrainingLongDescription");
                _TrainingLongDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TrainingLongDescription");
                OnTrainingLongDescriptionChanged();
            }
        }
        private global::System.String _TrainingLongDescription;
        partial void OnTrainingLongDescriptionChanging(global::System.String value);
        partial void OnTrainingLongDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
    }

    #endregion

    
}
